spring:
  application:
    name: SqlInjection

  datasource:
    url: jdbc:postgresql://localhost:5436/sql_injection_db
    username: sql_app_user
    password: sql_app_user
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

secret:
    jwt:
      string: b2Lg1fPqs92hJ3nT1VpXw!Gz0zPb3kXv7YvX@jJs9R8tT0h8K9V5e8b2v!hC
server:
  port: 8081
